server:
  port: 8082

spring:
  application:
    name: tracker-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/prepttracker}
    username: ${DATABASE_USER:preptuser}
    password: ${DATABASE_PASSWORD:preptpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/tracker
    baseline-on-migrate: false
    schemas: prept_tracker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
